# gen_build_stamp.py — PlatformIO pre-build extra_script.
#
# Writes .firmware/fsd_build_stamp.cpp with the wall-clock time and the git
# revision of THIS repository, so the boot banner describes the image that is
# actually running.
#
# ── Why this exists ──────────────────────────────────────────────────────────
#
# The banner used to print __DATE__ " " __TIME__ from main.cpp. Those macros are
# frozen when main.cpp COMPILES, not when the image is built or flashed — so a
# build that only touched another translation unit kept main.cpp's old .o and
# reported a stale date. Measured 2026-08-23: blackbox.cpp changed, the image
# was rebuilt and flashed, and the board booted saying "Build: Aug 21".
#
# 🔴 That is the worst kind of wrong output: the boot banner is the FIRST thing
# read when a board misbehaves, and a stale date sends you to re-flash an image
# that was already correct. This repository has been bitten by the same shape
# before — a banner advertising a compiled-out feature (fork PR #53).
#
# ── Why a generated .cpp and not a -D flag ───────────────────────────────────
#
# A build flag would work, but build_flags are part of EVERY object's signature,
# so a stamp that changes each run would force a full rebuild of all sources on
# every build, on all eight boards. A generated file is a dependency of exactly
# one tiny translation unit: only it recompiles, then the image relinks.
#
# ── Why generated content and not `touch` ────────────────────────────────────
#
# 🔴 Touching the file is NOT enough. SCons (PlatformIO's build engine) decides
# staleness with MD5-timestamp: a newer mtime with identical content can still
# be treated as unchanged, so the rebuild would be skipped and the stamp would
# silently stay stale — the exact failure this script exists to remove. Writing
# genuinely different content makes the rebuild unconditional.
Import("env")
import os
import subprocess
import time

# SCons execs this script rather than importing it, so __file__ is NOT defined
# here -- PlatformIO hands the project root over as PROJECT_DIR instead.
FIRMWARE_DIR = os.path.join(env["PROJECT_DIR"], ".firmware")
OUT = os.path.join(FIRMWARE_DIR, "fsd_build_stamp.cpp")


def _git(*args):
    """Run a git command in this repo. Returns "" when git or the repo is absent.

    Never raises: a missing git must degrade the stamp, not break the build.
    """
    try:
        out = subprocess.check_output(
            ["git"] + list(args),
            cwd=FIRMWARE_DIR,
            stderr=subprocess.STDOUT,
        )
        return out.decode("utf-8", "replace").strip()
    except Exception:
        return ""


def _revision():
    """Short revision, with -dirty when the working tree has uncommitted edits.

    🔴 The dirty marker is the load-bearing half. A bare hash on a modified tree
    names the last COMMIT, not the code in the image — which is precisely the
    situation this banner is consulted in (a change made, built, flashed, and
    not yet committed).
    """
    rev = _git("rev-parse", "--short=8", "HEAD")
    if not rev:
        return "nogit"
    # --porcelain prints one line per changed path; any output means dirty.
    if _git("status", "--porcelain", "--untracked-files=no"):
        rev += "-dirty"
    return rev


stamp = "%s %s" % (time.strftime("%Y-%m-%d %H:%M:%S"), _revision())

# 🔴 `extern` on the definition is required, not decorative. In C++ a const
# array at namespace scope has INTERNAL linkage by default, so plain
# `const char FSD_BUILD_STAMP[] = ...` would be private to this translation
# unit and main.cpp would fail to link against it.
body = (
    "// GENERATED by esp32/gen_build_stamp.py before every build. Do not edit;\n"
    "// do not commit. Regenerating it is what keeps the boot banner honest.\n"
    '#include "fsd_build_stamp.h"\n'
    'extern const char FSD_BUILD_STAMP[];\n'
    'const char FSD_BUILD_STAMP[] = "%s";\n' % stamp
)

# Write unconditionally. Identical content on two builds in the same second is
# possible and harmless; SCons then correctly skips the recompile because
# nothing actually changed.
with open(OUT, "w") as f:
    f.write(body)

print("[stamp] %s" % stamp)
